version: "3.1"

services:
  postgresql:
    container_name: bazar_data
    image: postgres
    ports:
      - "5446:5432"
    volumes:
      - ./scripts/init.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./database/data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=inacap123
      - POSTGRES_DB=bazar
  adminer:
    container_name: bazar_adminer
    image: adminer
    restart: always
    ports:
      - 8060:8080
    environment:
      - ADMINER_DESIGN=pepa-linha

  bazar_app:
    container_name: bazar_app
    image: bazar_app
    restart: on-failure
    environment:
      - DB_HOST=bazar_data
      - DB_PORT=5432
      - DB_DATABASE=bazar
      - DB_PASSWORD=inacap123
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 3601:3000
